package com.digitalbook.book.repository;

public class SqlQueries {

	public final static String CREATEBOOKBYAUTHOR = "INSERT INTO BOOK (BOOKTITLE,BOOKCODE,AUTHORID,PRICE,CATEGORY,PUBLISHER,LOGO,AUDIOURL,CONTENT,ISACTIVE,UPDATEDON,CREATEDBY,UPDATEDBY,CREATEDON, PUBLISHDATE) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
	
	public final static String EXITSBYAUTHORBOOKTITLE = "SELECT COUNT(*) FROM BOOK WHERE AUTHORID =? AND BOOKTITLE=?";
	
	public final static String UPDATEBOOK = "UPDATE BOOK SET BOOKCODE= ? , UPDATEDON=? WHERE ID=?";
	
	public final static String BLOCKBOOK = "UPDATE BOOK SET ISACTIVE=?, UPDATEDON=? WHERE ID=?";
	
	public final static String UNBLOCKBOOK = "UPDATE BOOK SET ISACTIVE= ? , UPDATEDON=? WHERE ID=?";
	
	public final static String SEARCHBOOK = "SELECT  *, BS.ID AS SUBSCRIBEID FROM BOOK B, BOOKSUBSCRIPTION BS WHERE BS.USERID=? AND BS.BOOKID=B.ID AND B.ISACTIVE=1 AND BS.ISACTIVE=1";
	
	public final static String SUBSCRIPTIONBOOK = "INSERT INTO BOOKSUBSCRIPTION (USERID, ISACTIVE, BOOKID)  VALUES(?,?,?)";
	
	public final static String AUTHORBOOKS = "SELECT * FROM (SELECT B.* , COUNT(BS.BOOKID) AS SUBSCRIBEDCOUNT FROM BOOK B LEFT JOIN BOOKSUBSCRIPTION BS ON BS.BOOKID = B.ID AND BS.ISACTIVE=1 GROUP BY B.AUTHORID , B.ID)  A WHERE A.AUTHORID=?";
	
	public final static String GETBOOKBYID = "SELECT * FROM BOOK WHERE id=?";
	
	public final static String UNSUBSCRIPTIONBOOK = "DELETE FROM BOOKSUBSCRIPTION WHERE ID=?";

	public final static String SEARCHBOOKS = "SELECT B.* FROM (SELECT * FROM BOOK WHERE PUBLISHDATE LIKE '%?%' AND BOOKTITLE LIKE '%?%' AND PUBLISHER LIKE '%?%' AND ISACTIVE=1) AS B , BOOKSUBSCRIPTION BS WHERE BS.USERID=? AND B.ID=BS.BOOKID AND BS.ISACTIVE=1";
}
